In [ ]:
from google.colab import drive
drive.mount('/content/drive')

In [ ]:
from google.colab import drive

In [ ]:
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [ ]:
import pandas as pd

In [ ]:
data = pd.read_csv('/content/drive/MyDrive/datascience/Crop_Recommendation.csv')

In [ ]:
raw=pd.read_csv('/content/drive/MyDrive/datascience/my_file.csv')
data2=raw.copy()

In [ ]:
print("rows columns:",data.shape)

rows columns: (2200, 8)

In [ ]:
data.head()

,Nitrogen,Phosphorus,Potassium,Temperature,Humidity,pH_Value,Rainfall,Crop
0,90,42,43,20.879744,82.002744,6.502985,202.935536,Rice
1,85,58,41,21.770462,80.319644,7.038096,226.655537,Rice
2,60,55,44,23.004459,82.320763,7.840207,263.964248,Rice
3,74,35,40,26.491096,80.158363,6.980401,242.864034,Rice
4,78,42,42,20.130175,81.604873,7.628473,262.717340,Rice

In [ ]:
data.head()

,Nitrogen,Phosphorus,Potassium,Temperature,Humidity,pH_Value,Rainfall,Crop
0,90,42,43,20.879744,82.002744,6.502985,202.935536,Rice
1,85,58,41,21.770462,80.319644,7.038096,226.655537,Rice
2,60,55,44,23.004459,82.320763,7.840207,263.964248,Rice
3,74,35,40,26.491096,80.158363,6.980401,242.864034,Rice
4,78,42,42,20.130175,81.604873,7.628473,262.717340,Rice

In [ ]:
df = data.copy()

In [ ]:
df.shape

(2200, 8)

In [ ]:
df.head()

,Nitrogen,Phosphorus,Potassium,Temperature,Humidity,pH_Value,Rainfall,Crop
0,90,42,43,20.879744,82.002744,6.502985,202.935536,Rice
1,85,58,41,21.770462,80.319644,7.038096,226.655537,Rice
2,60,55,44,23.004459,82.320763,7.840207,263.964248,Rice
3,74,35,40,26.491096,80.158363,6.980401,242.864034,Rice
4,78,42,42,20.130175,81.604873,7.628473,262.717340,Rice

In [ ]:
#Inspections
print("Shape (rows,columns):",df.shape)

Shape (rows,columns): (2200, 8)

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2200 entries, 0 to 2199
Data columns (total 8 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Nitrogen     2200 non-null   int64
 1   Phosphorus   2200 non-null   int64
 2   Potassium    2200 non-null   int64
 3   Temperature  2200 non-null   float64
 4   Humidity     2200 non-null   float64
 5   pH_Value     2200 non-null   float64
 6   Rainfall     2200 non-null   float64
 7   Crop         2200 non-null   object
dtypes: float64(4), int64(3), object(1)
memory usage: 137.6+ KB

In [ ]:
for col in df.columns:
  print(repr(col))

'Nitrogen'
'Phosphorus'
'Potassium'
'Temperature'
'Humidity'
'pH_Value'
'Rainfall'
'Crop'

In [ ]:
for col in data2.columns:
  print(repr(col))

word="Actual\xa0gross"
print(repr(re.sub(r'[^\w]+','_',word.replace('\xa0',' ').strip().lower()).strip('_')))

'Rank'
'Peak'
'All Time Peak'
'Actual\xa0gross'
'Adjusted\xa0gross (in 2022 dollars)'
'Artist'
'Tour title'
'Year(s)'
'Shows'
'Average gross'
'Ref.'
'actual_gross'

In [ ]:
df.columns

Index(['Nitrogen', 'Phosphorus', 'Potassium', 'Temperature', 'Humidity',
       'pH_Value', 'Rainfall', 'Crop'],
      dtype='object')

In [ ]:
import re
def to_snake_case(name:str) -> str:
  name=name.replace("\xa0", " ")
  name=name.strip().lower()
  name= re.sub(r"[^\w]+","_",name)
  return name.strip("_")
def to_snake(name):
  return re.sub(r"[^\w]+",'_',name.replace('\xa0',' ').strip().lower()).strip('_')

In [ ]:
df.columns=[to_snake(c) for c in df.columns]
df.columns.tolist()

['nitrogen',
 'phosphorus',
 'potassium',
 'temperature',
 'humidity',
 'ph_value',
 'rainfall',
 'crop']

In [ ]:
fn_pattern=r"\[[^\]*\]"

In [ ]:
fn_pattern = r'\[[^\]]+\]'
fn_counts = (df.astype('string').apply(lambda col: col.str.contains(fn_pattern, regex=True, na=False)).sum())
fn_count=(data2.astype('string').apply(lambda col: col.str.contains(fn_pattern,regex=True,na=False)).sum())
fn_count

Rank                                 0
Peak                                 7
All Time Peak                        5
Actual gross                         2
Adjusted gross (in 2022 dollars)     0
Artist                               0
Tour title                           2
Year(s)                              0
Shows                                0
Average gross                        0
Ref.                                20
dtype: Int64

In [ ]:
fn_counts

nitrogen       0
phosphorus     0
potassium      0
temperature    0
humidity       0
ph_value       0
rainfall       0
crop           0
dtype: Int64

In [ ]:
df.head()

,nitrogen,phosphorus,potassium,temperature,humidity,ph_value,rainfall,crop
0,90,42,43,20.879744,82.002744,6.502985,202.935536,Rice
1,85,58,41,21.770462,80.319644,7.038096,226.655537,Rice
2,60,55,44,23.004459,82.320763,7.840207,263.964248,Rice
3,74,35,40,26.491096,80.158363,6.980401,242.864034,Rice
4,78,42,42,20.130175,81.604873,7.628473,262.717340,Rice

In [ ]:
raw.head()

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]

In [ ]:
data2=raw.copy()

In [ ]:
data2.head()

,Rank,Peak,All Time Peak,Actual gross,Adjusted gross (in 2022 dollars),Artist,Tour title,Year(s),Shows,Average gross,Ref.
0,1,1,2,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1,7[2],"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1[4],2[5],"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2[7],10[7],"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2[4],NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]

In [ ]:
data2.columns=[re.sub(r'[^\w]+','_',col.replace('\xa0','_').strip().lower()).strip('_') for col in data2.columns]
data2.columns.tolist()

['rank',
 'peak',
 'all_time_peak',
 'actual_gross',
 'adjusted_gross_in_2022_dollars',
 'artist',
 'tour_title',
 'year_s',
 'shows',
 'average_gross',
 'ref']

In [ ]:
fn_pat=r'\[[^\]]+\]'
fn_coun=data2.astype(str).apply(lambda col: col.str.contains(fn_pat,regex=True,na=False))
fn_coun.sum()

rank                               0
peak                               7
all_time_peak                      5
actual_gross                       2
adjusted_gross_in_2022_dollars     0
artist                             0
tour_title                         2
year_s                             0
shows                              0
average_gross                      0
ref                               20
dtype: int64

In [ ]:
data2["peak"]=data2["peak"].astype(str).str.extract(r'(\d+)').astype(float)
data2["all_time_peak"]=data2["all_time_peak"].astype(str).str.extract(r'(\d+)').astype(float)
data2["peak"].head()

0    1.0
1    1.0
2    1.0
3    2.0
4    2.0
Name: peak, dtype: float64

In [ ]:
data2["all_time_peak"].head()

0     2.0
1     7.0
2     2.0
3    10.0
4     NaN
Name: all_time_peak, dtype: float64

In [ ]:
data2.head()

,rank,peak,all_time_peak,actual_gross,adjusted_gross_in_2022_dollars,artist,tour_title,year_s,shows,average_gross,ref
0,1,1.0,2.0,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1.0,7.0,"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1.0,2.0,"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2.0,10.0,"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2.0,NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]

In [ ]:
data2.columns.tolist()

['rank',
 'peak',
 'all_time_peak',
 'actual_gross',
 'adjusted_gross_in_2022_dollars',
 'artist',
 'tour_title',
 'year_s',
 'shows',
 'average_gross',
 'ref']

In [ ]:
data2.head()

,rank,peak,all_time_peak,actual_gross,adjusted_gross_in_2022_dollars,artist,tour_title,year_s,shows,average_gross,ref
0,1,1.0,2.0,"$780,000,000","$780,000,000",Taylor Swift,The Eras Tour †,2023–2024,56,"$13,928,571",[1]
1,2,1.0,7.0,"$579,800,000","$579,800,000",Beyoncé,Renaissance World Tour,2023,56,"$10,353,571",[3]
2,3,1.0,2.0,"$411,000,000","$560,622,615",Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,"$4,835,294",[6]
3,4,2.0,10.0,"$397,300,000","$454,751,555",Pink,Beautiful Trauma World Tour,2018–2019,156,"$2,546,795",[7]
4,5,2.0,NaN,"$345,675,146","$402,844,849",Taylor Swift,Reputation Stadium Tour,2018,53,"$6,522,173",[8]

In [ ]:
financial_cols=['actual_gross','adjusted_gross_in_2022_dollars','average_gross']
for col in financial_cols:
  data2[col]=data2[col].astype('string').str.replace(r'[\$,]','',regex=True).str.replace(r'\[[^\]]+\]','',regex=True)
  data2[col]=pd.to_numeric(data2[col],errors='coerce')

In [ ]:
data2.head()

,rank,peak,all_time_peak,actual_gross,adjusted_gross_in_2022_dollars,artist,tour_title,year_s,shows,average_gross,ref
0,1,1.0,2.0,780000000,780000000,Taylor Swift,The Eras Tour †,2023–2024,56,13928571,[1]
1,2,1.0,7.0,579800000,579800000,Beyoncé,Renaissance World Tour,2023,56,10353571,[3]
2,3,1.0,2.0,411000000,560622615,Madonna,Sticky & Sweet Tour ‡[4][a],2008–2009,85,4835294,[6]
3,4,2.0,10.0,397300000,454751555,Pink,Beautiful Trauma World Tour,2018–2019,156,2546795,[7]
4,5,2.0,NaN,345675146,402844849,Taylor Swift,Reputation Stadium Tour,2018,53,6522173,[8]